# Generated by Django 5.2.4 on 2025-07-13 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GradeTamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('N', 'Normal'), ('P', 'Plus'), ('U', 'Numeração')], default='N', max_length=1)),
                ('tamanhos', models.CharField(help_text='Ex: P,M,G,GG ou 36,38,40', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo_interno', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.PositiveIntegerField(default=0)),
                ('peso', models.DecimalField(decimal_places=3, default=0.0, help_text='Em kg', max_digits=6)),
                ('altura', models.DecimalField(decimal_places=2, default=0.0, help_text='Em cm', max_digits=6)),
                ('largura', models.DecimalField(decimal_places=2, default=0.0, help_text='Em cm', max_digits=6)),
                ('ncm', models.CharField(blank=True, max_length=10, null=True)),
                ('cest', models.CharField(blank=True, max_length=10, null=True)),
                ('cfop', models.CharField(blank=True, max_length=10, null=True)),
                ('desconto_maximo', models.DecimalField(blank=True, decimal_places=2, help_text='Desconto máximo permitido (%)', max_digits=5, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.categoria')),
                ('grade_tamanho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.gradetamanho')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.marca')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produtos/')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='produtos.produto')),
            ],
        ),
        migrations.CreateModel(
            name='VariacaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(blank=True, max_length=50)),
                ('tamanho', models.CharField(blank=True, max_length=10)),
                ('estoque', models.PositiveIntegerField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='produtos.produto')),
            ],
        ),
    ]
