# Generated by Django 5.2.4 on 2025-07-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem_principal',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
