# Generated by Django 4.2.11 on 2025-07-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_remove_variacaoproduto_tipo_tamanho_produto_altura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacaoproduto',
            name='cor',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='variacaoproduto',
            name='tamanho',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
