# Generated by Django 4.2.11 on 2025-07-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_variacaoproduto_cor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacaoproduto',
            name='imagem_cor',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/variacoes/'),
        ),
    ]
